### ISSUE TITLE
Character counter showing a 500 char limit, but the limit in my server is 5000 characters

### ISSUE THREAD

**Issue by ernestomiquel** [metabolist/metatext#202] opened 2022-11-20 20:56 UTC
**Describe the bug**

The character counter while creating a new post shows a 500 char limit, despite the fact that the limit in my server is 5000 characters, and it works fine in the web interface and other apps. I believe, but not completely shure, that this behavior started when my server updated to mastodon 4.0 (or it might have been a recent Metatext update). 

**To Reproduce**
1. Go to create new post
2. See wrong character limit (500)

**Expected behavior**
I expected to see a 5000 character limit 

**Screenshots**

**(please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.0
 - App Version 1.6.0

**Additional context**

**Comment by bramus** [comment] 2022-11-20 21:02
Duplicate of https://github.com/metabolist/metatext/issues/103

**Closed** 2022-11-21 00:40 UTC
Labels: duplicate
