### ISSUE TITLE
Muting accounts causes app to crash

### ISSUE THREAD

**Issue by t3rrrrrible** [metabolist/metatext#247] opened 2022-11-25 21:12 UTC
iOS 16.1.1
Metatext 1.7.0 (3)

EDIT: muting from the Home/Local/Fed timeline directly to a post does NOT crash the app, navigating to the profile from the timeline and muting the account causes the crash. 

Going to the account page from muted users and trying to re-mute does not cause a crash. Searching the account and muting does not cause a crash.

**Comment by t3rrrrrible** [comment] 2022-11-26 03:15
Finding the account again and re-muting also causes app to crash.

**Comment by alexbbrown** [comment] 2022-11-26 19:34
This is a dupe of #48 

Thanks for filing this bug report!

Another way to raise visibility for an issue is to check for existing reports and add your evidence to those.  For example, search for "Mute" in the issue page.

**Closed as completed** 2022-11-26 22:15 UTC
Labels: duplicate
