### ISSUE TITLE
Deleted posts persist in cache

### ISSUE THREAD

**Issue by aaronshaf** [metabolist/metatext#57] opened 2022-01-13 02:36 UTC
**Describe the bug**
When a user deletes their post, even upon refresh it remains in Metatext.

**To Reproduce**
1. Create a post.
2. Load that post in Metatext.
3. Delete the in a web interface.
4. Refresh your timeline in the Metatext app.
5. Note that the deleted post still shows.

**(please complete the following information):**
 - Device: Recent iPhone :)
 - App Version: Fresh install from App Store :)

**Comment by jzzocc** [comment] 2022-11-12 19:18
Duplicate of #15

**Closed by jzzocc** 2022-11-12 19:18 UTC
Labels: duplicate
